name = "web-archive"
pages_build_output_dir = "../../dist/service"
compatibility_flags = [ "nodejs_compat_v2" ]
compatibility_date = "2024-10-21"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "web-archive"

[[d1_databases]]
binding = "DB"
database_name = "web-archive"
database_id = "794794db-f011-43f6-900b-5fb7159ee4cb"
migrations_dir = './src/sql/migrations'

[ai]
binding = "AI"
