name = "web-archive"
pages_build_output_dir = "../../dist/service"
compatibility_flags = [ "nodejs_compat_v2" ]
compatibility_date = "2024-10-21"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "web-archive"

[[d1_databases]]
binding = "DB"
database_name = "web-archive"
database_id = "a1e7ebcb-33f9-459c-ad73-8e0f8244f4c5"
migrations_dir = './src/sql/migrations'

[ai]
binding = "AI"
